config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'questions#index'

  resources :questions do
    resources :answers, shallow: true, except: %i[index show]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :body, presence: true

  belongs_to :user

  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, :body, presence: true

  belongs_to :user

  has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :answers

  def author_of?(resource)
    resource.user_id == id
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: %i[new create destroy]

  expose :question, -> { Question.find(params[:question_id]) }
  expose :answers, -> { question.answers.reject(&:new_record?) }
  expose :answer,
         build: ->(params, _scope) { question.answers.new(params.merge(user_id: current_user.id)) }

  def create
    if answer.save
      redirect_to answer.question, notice: 'Answer create successfully'
    else
      render 'questions/show'
    end
  end

  def update
    if answer.update(answer_params)
      redirect_to answer
    else
      render :edit
    end
  end

  def destroy
    if current_user.author_of?(answer)
      answer.destroy
      flash[:notice] = 'Answer delete successfully'
    else
      flash[:alert] = "You can not delete someone else's answer"
    end
    redirect_to answer.question
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create destroy]

  expose :questions, -> { Question.all }
  expose :question,
         build: ->(params, _scope) { current_user.questions.new(params) }
  expose :answers, -> { question.answers }
  expose :answer, -> { question.answers.new }

  def create
    if question.save
      redirect_to question, notice: 'Question create successfully'
    else
      render :new
    end
  end

  def update
    if question.update(question_params)
      redirect_to question
    else
      render :edit
    end
  end

  def destroy
    if current_user.author_of?(question)
      question.destroy
      flash[:notice] = 'Question delete successfully'
    else
      flash[:alert] = "You can not delete someone else's question"
    end
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
li
  = answer.body
  - if current_user&.author_of?(answer)
    = link_to 'Delete Answer', answer_path(answer), method: :delete

app/views/answers/_form.html.slim
= render 'shared/errors', entity: answer

= form_with model: [question, answer], local: true do |f|
  p
    = f.label :body
    = f.text_area :body, size: "60x12"
  p
    = f.submit 'Create Answer'

app/views/layouts/_nav.html.slim
ul
  - if user_signed_in?
    li = link_to 'Sign Out', destroy_user_session_path, method: :delete
  - else
    li = link_to 'Sign In', new_user_session_path
    li = link_to 'Sign Up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Qna
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/nav'
    p = notice
    p = alert
    = yield

app/views/questions/_question.html.slim
li = link_to question.title, question_path(question)

app/views/questions/index.html.slim
- if user_signed_in?
  = link_to "Ask question", new_question_path

ul
  = render questions

app/views/questions/new.html.slim
= render "shared/errors", entity: question

= form_with model: question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body, size: "60x12"
  p
    = f.submit 'Create Question'

app/views/questions/show.html.slim
p = question.title
p = question.body

- if current_user&.author_of?(question)
  = link_to 'Delete Question', question_path(question), method: :delete

ul
  = render answers

- if user_signed_in?
  = render 'answers/form'

app/views/shared/_errors.html.slim
- if entity&.errors.present?
  ul
    - entity.errors.full_messages.each do |msg|
      li
        = msg